import type { Metadata } from "next";
import "./globals.css";
import MenuBar from "@/components/MenuBar";
import { AppContextProvider } from "@/contexts/AppContext";
import DarkMode from "@/components/DarkMode";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className="antialiased font-sans bg-white dark:bg-black text-zinc-900 dark:text-zinc-100">
        <AppContextProvider>
          <DarkMode />
          <MenuBar />
          {children}

          <footer className="w-full mt-8 flex flex-col items-center text-center text-zinc-600 dark:text-zinc-300 text-sm">
            <hr className="w-full border-zinc-200 dark:border-zinc-800 mb-4" />
            <span>
              Pokédex App &copy; {new Date().getFullYear()} - Hecho con <span className="text-blue-500">Next.js</span> y amor por Pokémon.
            </span>
          </footer>
        </AppContextProvider>
      </body>
    </html>
  );
}
