import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {children}: Readonly<{children: React.ReactNode}> ){
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`antialiased`} >
        <header>
          <nav className="flex gap-2 justify-center">
            <Link href="/" className="hover:bg-amber-200">Inicio</Link>
            <Link href="/about" className="hover:bg-amber-200">Acerca de</Link>
            <Link href="/contact" className="hover:bg-amber-200">Contacto</Link>
          </nav>
        </header>
        {children}
        <footer>Created by Francisco Romero</footer>
      </body>
    </html>
  );
}
